moduleName: 'game'
requiredModules:
  api: true
dwellers:
  Game: true
mixins:
  Api:
    api: true
api:
  commands:
    greet:
      description: 'Greeting command'
      params:
        age:
          description: 'Your age'
        name:
          description: 'Your name'
          required: true
