moduleName: 'pvpServer'
requiredModules:
  api: true
  mongo: true
  pvpServer/player: true
  pvpServer/game: true
  pvpServer/matchmaker: true

dwellers:
  PvpServer:
    id: 'string'
    mixins:
      pvpServer/pvpServer: true
  Core:
    mixins:
      pvpServer/core: true
  Api:
    mixins:
      pvpServer/api: true
      
api:
  paths:
    core:
      commands:
        reloadPvpServers: true
    game:
      params: 
        gameId:
          type: 'string'
          required: true
      commands:
        getGameInfo:
          description: 'Returns game info'
        getGameVersion:
          description: 'Return content version'
          params: 
            version:
              type: 'string'
              description: 'Game version'
              