moduleName: 'engine'
# requiredModules: 
  # engine/object: true
mixins:
  Engine:
    engine: true
  Api:
    api: true
  Core:
    core: true
dwellers:
  Engine: true


api:
  paths:
    engine:
      params:
        gameId:
          description: 'Game Id'
          type: 'string'
          required: true
      paths:
        getContent:
          description: 'Returns project content'
          params:
            objects:
              type: 'bool'
              description: 'Set to true if you want to receive objects in response'
            templates:
              type: 'bool'
              description: 'Set to true if you want to receive template schemas in response'
        # restore:
        #   description: 'Returns project content'
        #   params:
        #     src:
        #       required: true
        #       type: 'json'
        #       description: 'Source JSON to restore content from'
        # migrate:
        #   description: 'Content migration payload'
        #   params: 
        #     objects: 
        #       type: 'array(json)'
        #       description: 'Objects to be edited'
        #     newObjects: 
        #       type: 'array(json)'
        #       description: 'Objects to be created'
        #     templates: 
        #       type: 'array(json)'
        #       description: 'Templates to be edited'
        #     newTemplates: 
        #       type: 'array(json)'
        #       description: 'Templates to be created'
        # getConfig:
        #   description: 'Returns project config'
        # setConfig:
        #   description: 'Sets project config'
        #   params:
        #     fields:
        #       type: 'json'
        #       description: 'New config data'
        #       required: true
        # release:
        #   description: 'Releases new version of the game to public'
        #   params:
        #     contentWeb:
        #       type: 'json'
        #       description: 'Compiled content for web brick runtime'
        #       required: true
        #     contentUnity:
        #       type: 'json'
        #       description: 'Compiled content for thin Unity client'
        #       required: true
        #     contentMeta:
        #       type: 'json'
        #       description: 'Compiled content for game page'
        #       required: true
        # sync:
        #   description: 'Synchronizes game content with source project'

tests:
  testEngineApi: true