moduleName: 'engine'
requiredModules: 
  engine/object: true
  engine/template: true
  engine/user: true
mixins:
  Engine:
    engine: true
  Api:
    api: true
  Core:
    core: true
dwellers:
  Engine: true


api:
  paths:
    core:
      commands:
        reloadEngines: true
    engine:
      access:
        pubkey:
          description: 'Public key of user'
          type: 'Pubkey'
          required: true
      params:
        gameId:
          description: 'Game Id'
          type: 'string'
          required: true
      commands:
        getContent:
          public: true
          description: 'Returns project content'
          params:
            objects:
              type: 'bool'
              description: 'Set to true if you want to receive objects in response'
            templates:
              type: 'bool'
              description: 'Set to true if you want to receive template schemas in response'
        restore:
          description: 'Imports full content from JSON'
          params:
            src:
              required: true
              type: 'json'
              description: 'Source JSON to restore content from'
        migrate:
          description: 'Content migration payload'
          params: 
            objects: 
              type: 'array(json)'
              description: 'Objects to be edited'
            newObjects: 
              type: 'array(json)'
              description: 'Objects to be created'
            templates: 
              type: 'array(json)'
              description: 'Templates to be edited'
            newTemplates: 
              type: 'array(json)'
              description: 'Templates to be created'
        getConfig:
          public: true
          description: 'Returns project config'
        setConfig:
          description: 'Sets project config'
          params:
            fields:
              type: 'json'
              description: 'New config data'
              required: true
        sync:
          description: 'Synchronizes game content with source project'
        release:
          description: 'Releases new version of the game to gameServer'
          params:
            content:
              type: 'json'
              description: 'Compiled content'
              required: true

tests:
  testEngineApi: true