moduleName: 'engine/user'

dwellers:
  Api:
    mixins:
      engine/user/api: true

api:
  paths:
    engine:
      paths:
        user:
          commands:
            checkAccess:
              description: 'Get user access mask'
            get:
              description: 'Get user data'
            update:
              params:
                fields:
                  description: 'Fields to update'
                  type: 'json'
                  required: true
          
tests:
  testUserApi: true