moduleName: 'gameServer/game'
requiredModules:
  web/socket: true
  gameServer/player: true

dwellers:
  Game: 
    id: 'string'
    mixins:
      gameServer/game/game: true
  Player:
    mixins:
      gameServer/game/player: true
  GameServer:
    mixins:
      gameServer/game/gameServer: true

tests:
  testGame: true
  testSaveLoad: true
  testReconnect: true
    