moduleName: 'pvpServer/game'
requiredModules:
  web/socket: true
  pvpServer/player: true

dwellers:
  Game: 
    id: 'string'
    mixins:
      pvpServer/game/game: true
  Player:
    mixins:
      pvpServer/game/player: true
  PvpServer:
    mixins:
      pvpServer/game/pvpServer: true

tests:
  testGame: true
  testSaveLoad: true
  testReconnect: true
    