moduleName: 'unityBuilds'
requiredModules:
  api: true
mixins:
  Api:
    api: true
api:
  paths:
    system:
      commands:
        getUnityBuild:
          params: 
            buildId:
              type: 'string'
              required: true
