moduleName: 'unityBuilds'
requiredModules:
  api: true
mixins:
  Core:
    core: true
api:
  paths:
    getUnityBuild:
      params: 
        buildId:
          type: 'string'
          required: true
