moduleName: 'core'
requiredModules:
  api: true
  gameServer: true
  mongo: true
  engine: true
  websocket: true
  unityBuilds: true
  forge: true

dwellers:
  Core:
    mixins:
      core/core: true
  Api:
    mixins:
      core/api: true

api:
  paths:
    core:
      params:
        userId:
          type: 'pubkey'
          required: true
      commands:
        eval:
          params:
            code:
              type: 'javascript'
              required: true

tests:
  testDisableMixin: true
