moduleName: 'unityBuilds'
requiredModules:
  api: true

dwellers:
  Api:
    mixins:
      unityBuilds/api: true
      
api:
  .commands:
    getUnityBuild:
      params: 
        buildId:
          type: 'string'
          required: true
