moduleName: 'game'
requiredModules:
  api: true
  gameServer/game: true
  gameServer/player: true
  gameServer/matchmaker: true
  unityBuilds: true
dwellers:
  GameServer: true
mixins:
  GameServer:
    gameServer: true
  Core:
    core: true
  ApiRequest:
    apiRequest: true
api:
  paths:
    game:
      params: 
        gameId:
          type: 'string'
          required: true
      paths:
        getGameInfo:
          description: 'Returns game info'
        getGameVersion:
          description: 'Return content version'
          params: 
            version:
              type: 'string'
              description: 'Game version'
        # findMatch:
        #   description: 'Find new match using matchmaker'
        #   params: 
        #     nfts:
        #       type: 'array(string)'
        #       description: 'List of player nfts'
        #     gameVersion:
        #       type: 'int'
        #       description: 'Version of the game. Latest if not specified'
        # joinMatch:
        #   params:
        #     matchId:
        #       type: 'string'
        #       required: true
        # leaveMatch:
        #   params:
        #     matchId:
        #       type: 'string'
        #       description: 'matchId'
        #       required: true

        # bugreport:
        #   description: 'Send bug report'
        #   params:
        #     payload:
        #       description: 'JSON serialized payload with report'
        #       type: 'json'
        #       required: true
