moduleName: 'project/pvpServer/match/gameState'
dwellers:
  Match: 
    mixins:
      project/pvpServer/match/gameState/match: true
      project/pvpServer/match/gameState/mixin: true
tests:
  testGameState: true
