moduleName: 'project/engine'
requiredModules: 
  api: true
  project/engine/object: true
  project/engine/template: true
  project/engine/user: true
  
dwellers:
  Api:
    mixins:
      project/engine/api: true
  Core:
    mixins:
      project/engine/core: true
  Project:
    mixins:
      project/engine/project: true
api:
  engine:
    .access:
      pubkey:
        description: 'Public key of user'
        type: 'Pubkey'
        required: true
    .params:
      projectId:
        description: 'Game Id'
        type: 'string'
        required: true
    .commands:
      getContent:
        public: true
        description: 'Returns project content'
        params:
          objects:
            type: 'bool'
            description: 'Set to true if you want to receive objects in response'
          templates:
            type: 'bool'
            description: 'Set to true if you want to receive template schemas in response'
      restore:
        description: 'Imports full content from JSON'
        params:
          src:
            required: true
            type: 'json'
            description: 'Source JSON to restore content from'
      migrate:
        description: 'Content migration payload'
        params: 
          objects: 
            type: 'array(json)'
            description: 'Objects to be edited'
          newObjects: 
            type: 'array(json)'
            description: 'Objects to be created'
          templates: 
            type: 'array(json)'
            description: 'Templates to be edited'
          newTemplates: 
            type: 'array(json)'
            description: 'Templates to be created'
      getConfig:
        public: true
        description: 'Returns project config'
      setConfig:
        description: 'Sets project config'
        params:
          fields:
            type: 'json'
            description: 'New config data'
            required: true
      sync:
        description: 'Synchronizes game content with source project'
      release:
        description: 'Releases new version of the game to pvpServer'
        params:
          content:
            type: 'json'
            description: 'Compiled content'
            required: true

# api:
#   paths:
#     core:
#       commands:
#         reloadEngines: true
#     engine:
#       access:
#         pubkey:
#           description: 'Public key of user'
#           type: 'Pubkey'
#           required: true
#       params:
#         gameId:
#           description: 'Game Id'
#           type: 'string'
#           required: true
      

tests:
  testEngineApi: true