moduleName: 'api'
requiredModules:
  http: true
  
dwellers:
  Api:
    id: 'string'
    mixins:
      api/api: true
  Core:
    mixins:
      api/core: true

api:
  commands:
    help:
      description: 'Shows Help'
      params: 
        paths:
          description: 'Shows API paths'
          type: 'boolean'

tests:
  testApi: true
  # testNestedCommand: true