moduleName: 'pvpServer/matchmaker'

dwellers:
  Matchmaker: 
    id: 'string'
    mixins: 
      pvpServer/matchmaker/matchmaker: 
        requiredMixins: 
          pvpServer/matchmaker/pvpServer: true
  PvpServer:
    mixins:
      pvpServer/matchmaker/pvpServer: true
  Player:
    mixins:
      pvpServer/matchmaker/player: true


tests:
  testMatchmaker: true
    