moduleName: 'gameServer/player'
requiredModules:
  websocket: true

dwellers: 
  Player: 
    id: 'string'
    mixins:
      gameServer/player/player: true
  WSConnection:
    mixins:
      gameServer/player/wsConnection: true
  GameServer:
    mixins:
      gameServer/player/gameServer: true
      
tests:
  testChallenge: true
