moduleName: 'gameServer/player'
requiredModules:
  web/socket: true

dwellers: 
  Player: 
    id: 'string'
    mixins:
      gameServer/player/player: true
  Socket:
    mixins:
      gameServer/player/socket: true
  GameServer:
    mixins:
      gameServer/player/gameServer: true
      
tests:
  testChallenge: true
