moduleName: 'project/engine/object'
requiredModules:
  api: true

dwellers:
  Api:
    mixins:
      project/engine/object/api: true

api:
  engine:
    template:
      object:
        .params:
          objectId:
            description: 'Object Id'
            type: 'string'
            required: true
        .commands:
          get:
            description: 'Returns object data'
          update:
            description: 'Updates object fields'
            params: 
              fields:
                description: 'JSON payload with new object fields'
                type: 'json'
                required: true
          clone:
            description: 'Clones object'
          delete:
            description: 'Deletes object'

tests:
  testObjectApi: true