moduleName: 'engine/object'
mixins:
  Api:
    api: true

api:
  paths:
    engine:
      paths:
        object:
          params:
            objectId:
              description: 'Object Id'
              type: 'string'
              required: true
          commands:
            get:
              description: 'Returns object data'
            update:
              description: 'Updates object fields'
              params: 
                fields:
                  description: 'JSON payload with new object fields'
                  type: 'json'
                  required: true
            clone:
              description: 'Returns object data'
            delete:
              description: 'Returns object data'
