moduleName: 'engine/object'
mixins:
  ApiRequest:
    api: true

api:
  paths:
    project:
      paths:
        object:
          params:
            gameId:
              description: 'Object Id'
              type: 'string'
              required: true
        get:
          description: 'Returns object data'
        update:
          description: 'Updates object fields'
          params: 
            fields:
              description: 'JSON payload with new object fields'
              type: 'json'
              required: true
        clone:
          description: 'Returns object data'
        delete:
          description: 'Returns object data'
