moduleName: 'matchmaker'
dwellers:
  Matchmaker: 
    id: 'string'
mixins:
  Matchmaker:
    matchmaker: true
  GameServer:
    gameServer: true
  Player:
    player: true
tests:
  testMatchmaker: true
    