moduleName: 'matchmaker'

dwellers:
  Matchmaker: 
    id: 'string'
    mixins: 
      gameServer/matchmaker/matchmaker: true
  GameServer:
    mixins:
      gameServer/matchmaker/gameServer: true
  Player:
    mixins:
      gameServer/matchmaker/player: true


tests:
  testMatchmaker: true
    