moduleName: 'bot'
requiredModules:
  gameServer/player: true
  gameServer/game: true
mixins:
  Player:
    player: true
tests:
  testBotRepeatFakeGame: true
  testBotRepeatLightmorGame: true
  testBotRandom: true
  testBotRandomPolygon: true
  # testViewPolygon: true 
  # testBot: true