moduleName: 'websocket'
requiredModules:
  http: true

dwellers:
  WSConnection: 
    id: 'string'
    mixins:
      websocket/wsConnection: true
  Core:
    mixins:
      websocket/core: true

tests:
  testWebSocket: true
