moduleName: 'api'
requiredModules:
  http: true
dwellers:
  Api:
    id: 'string'
mixins: 
  Core: 
    core: true
  Api:
    api: true
api:
  commands:
    help:
      description: 'Shows Help'
      params: 
        paths:
          description: 'Shows API paths'
          type: 'boolean'

tests:
  testHelp: true
  # testNestedCommand: true