moduleName: 'api'
requiredModules:
  http: true
dwellers:
  Api:
    id: 'string'
mixins: 
  Core: 
    core: true
  Api:
    api: true
api:
  paths:
    help: true
    test:
      paths:
        cmd: true

tests:
  testHelp: true
  # testNestedCommand: true