moduleName: 'api'
requiredModules:
  http: true
dwellers:
  Api:
    id: 'string'
mixins: 
  Core: 
    core: true
  Api:
    api: true
api:
  paths:
    api:
      commands:
        help:
          description: 'Shows Help'

tests:
  testHelp: true
  # testNestedCommand: true