moduleName: 'gameServer/game'
requiredModules:
  websocket: true
  gameServer/player: true
  gameServer/game/gameState: true
dwellers:
  Game: 
    id: 'string'
mixins:
  Game:
    game: true
  Player:
    player: true
  GameServer:
    gameServer: true

tests:
  testGame: true
  testSaveLoad: true
  testReconnect: true
    